// Export official drug datasets and DICT directly from E:\paxlovid.hta
export const proh: string[] = [
  "paxlovid",
  "molnupiravir",
  "veklury",
  "remdesivir",
  "isavuconazole",
  "thioridazine",
  "ziprasidone",
  "triamcinolone",
  "voriconazole",
  "zuclopenthixol",
  "cobicistat",
  "darunavir",
  "dasabuvir",
  "atazanavir",
  "aprepitant",
  "bedaquiline",
  "chloroquine",
  "orkambi",
  "dihydroergotamine",
  "elbasvir",
  "grazoprevir",
  "enzalutamide",
  "ergometrine",
  "ergonovine",
  "ergotamine",
  "glecaprevir",
  "pibrentasvir",
  "ivosidenib",
  "methylergometrine",
  "methylergonovine",
  "pimozide",
  "rifampicin",
  "rifapentine",
  "dronedarone",
  "amiodarone",
  "rifampicin",
  "rifapentine",
  "carbamazepine",
  "phenobarbital",
  "phenobarbitone",
  "phenytoin"
];
export const dont: string[] = [
  "umbralisib",
  "sonidegib",
  "pralsetinib",
  "pexidartinib",
  "pemigatinib",
  "mobocertinib",
  "larotrectinib",
  "entrectinib",
  "avanafil",
  "piroxicam",
  "macitentan",
  "bexarotene",
  "bulevirtide",
  "cariprazine",
  "cenobamate",
  "darifenacin",
  "eletriptan",
  "enasidenib",
  "finerenone",
  "flibanserin",
  "infigratinib",
  "ivacaftor/lumacaftor",
  "lomitapide",
  "lorlatinib",
  "naloxegol",
  "rimegepant",
  "silodosin",
  "sorafenib",
  "suvorexant",
  "tolvaptan",
  "toremifene",
  "ubrogepant",
  "vardenafil",
  "vorapaxar",
  "avapritinib",
  "crizotinib",
  "dabrafenib",
  "mitotane",
  "tazemetostat",
  "tepotinib",
  "topotecan",
  "vemurafenib",
  "cobimetinib",
  "regorafenib",
  "acalabrutinib",
  "alfuzosin",
  "aliskiren",
  "amiodarone",
  "apalutamide",
  "apixaban",
  "bepridil",
  "bosentan",
  "bosutinib",
  "carbamazepine",
  "carfentanil",
  "ciclosporin",
  "cyclosporine",
  "cisapride",
  "clonazepam",
  "clorazepate",
  "clozapine",
  "colchicine",
  "dextropropoxyphene",
  "diazepam",
  "dihydroergotamine",
  "disopyramide",
  "dofetilide",
  "domperidone",
  "dronedarone",
  "elbasvir",
  "grazoprevir",
  "enzalutamide",
  "eplerenone",
  "ergometrine",
  "ergonovine",
  "ergotamine",
  "estazolam",
  "everolimus",
  "flecainide",
  "flurazepam",
  "glecaprevir",
  "pibrentasvir",
  "halofantrine",
  "ibrutinib",
  "ivabradine",
  "ivosidenib",
  "lercanidipine",
  "lovastatin",
  "lumateperone",
  "lurasidone",
  "methylergometrine",
  "methylergonovine",
  "midazolam",
  "midostaurin",
  "neratinib",
  "pethidine",
  "meperidine",
  "phenobarbital",
  "phenobarbitone",
  "phenytoin",
  "pimozide",
  "primidone",
  "propafenone",
  "quetiapine",
  "quinidine",
  "ranolazine",
  "rifampicin",
  "rifapentine",
  "rivaroxaban",
  "salmeterol",
  "sildenafil",
  "simvastatin",
  "sirolimus",
  "st john's wort",
  "tacrolimus",
  "tadalafil",
  "ticagrelor",
  "triazolam",
  "venetoclax",
  "voclosporin"
];
export const pote: string[] = [
  "brinzolamide",
  "cabergoline",
  "cabozantinib",
  "darolutamide",
  "dutasteride",
  "duvelisib",
  "enfortumab vedotin",
  "erdafitinib",
  "etoposide",
  "fedratinib",
  "flutamide",
  "glasdegib",
  "guanfacine",
  "idelalisib",
  "isotretinoin",
  "lomustine",
  "octreotide",
  "paclitaxel",
  "polatuzumab vedotin",
  "ripretinib",
  "rucaparib",
  "selinexor",
  "solifenacin",
  "tisotumab vedotin",
  "vandetanib",
  "vilazodone",
  "zanubrutinib",
  "brentuximab vedotin",
  "bortezomib",
  "axitinib",
  "asciminib",
  "nimodipine",
  "almotriptan",
  "atomoxetine",
  "brigatinib",
  "brincidofovir",
  "cilostazol",
  "dexamfetamine",
  "dextroamphetamine",
  "gefitinib",
  "ivacaftor",
  "tezacaftor",
  "elexacaftor",
  "lapatinib",
  "lisdexamfetamine",
  "oxybutynin",
  "panobinostat",
  "pimavanserin",
  "ponatinib",
  "selpercatinib",
  "talazoparib",
  "tolterodine",
  "trastuzumab emtansine",
  "upadacitinib",
  "zolmitriptan",
  "hydroxyChloroquine",
  "digoxin",
  "ivacaftor",
  "abemaciclib",
  "acenocoumarol",
  "afatinib",
  "alfentanil",
  "alosetron",
  "alprazolam",
  "amlodipine",
  "amodiaquine",
  "amphetamine",
  "brexpiprazole",
  "aripiprazole",
  "atorvastatin",
  "betrixaban",
  "bupivacaine",
  "buspirone",
  "ceritinib",
  "chlordiazepoxide",
  "cladribine",
  "clarithromycin",
  "clobazam",
  "clopidogrel",
  "cocaine",
  "dabigatran",
  "dasatinib",
  "delamanid",
  "diamorphine",
  "diacetylmorphine",
  "dihydrocodeine",
  "diltiazem",
  "doxazosin",
  "ecstasy",
  "mdma",
  "edoxaban",
  "elvitegravir",
  "emtricitabine",
  "elvitegravir",
  "emtricitabine",
  "encorafenib",
  "erlotinib",
  "erythromycin",
  "ethosuximide",
  "etidocaine",
  "felodipine",
  "fentanyl",
  "fostamatinib",
  "ghb",
  "gamma-hydroxybutyrate",
  "gilteritinib",
  "glibenclamide",
  "glyburide",
  "heroin",
  "hydrocodone",
  "hydroxyzine",
  "iloperidone",
  "itraconazole",
  "ketamine",
  "ketoconazole",
  "labetalol",
  "lacidipine",
  "lidocaine",
  "lignocaine",
  "lopinavir",
  "ritonavir",
  "lsd",
  "lysergic acid diethylamide",
  "lumefantrine",
  "maraviroc",
  "mefloquine",
  "metamizole",
  "methamphetamine",
  "mexiletine",
  "morphine",
  "nateglinide",
  "nefazodone",
  "nicardipine",
  "nifedipine",
  "nilotinib",
  "nisoldipine",
  "nitrendipine",
  "olaparib",
  "ombitasvir",
  "paritaprevir",
  "ombitasvir",
  "paritaprevir",
  "oxycodone",
  "palbociclib",
  "pazopanib",
  "perampanel",
  "phenprocoumon",
  "piperaquine",
  "posaconazole",
  "quinine",
  "reboxetine",
  "repaglinide",
  "ribociclib",
  "rifabutin",
  "riociguat",
  "risperidone",
  "rosuvastatin",
  "ruxolitinib",
  "saxagliptin",
  "voxilaprevir",
  "sufentanil",
  "sultiame",
  "sunitinib",
  "tamsulosin",
  "telithromycin",
  "terazosin",
  "tofacitinib",
  "tramadol",
  "trazodone",
  "valsartan",
  "verapamil",
  "vinblastine",
  "vincristine",
  "warfarin",
  "zolpidem",
  "zotepine"
];
export const safe: string[] = [
  "norethisterone",
  "norethindrone",
  "norgestrel",
  "nystatin",
  "ocrelizumab",
  "ofloxacin",
  "olanzapine",
  "olmesartan",
  "olodaterol",
  "omeprazole",
  "ondansetron",
  "oseltamivir",
  "osimertinib",
  "oxandrolone",
  "oxazepam",
  "oxprenolol",
  "pantoprazole",
  "para-aminosalicylic acid",
  "paracetamol",
  "acetaminophen",
  "peginterferon beta-1a",
  "penicillins",
  "periciazine",
  "perindopril",
  "phenelzine",
  "pindolol",
  "piperacillin",
  "pipotiazine",
  "pitavastatin",
  "pomalidomide",
  "poppers",
  "amyl nitrate",
  "potassium",
  "pramipexole",
  "prasugrel",
  "pravastatin",
  "prazosin",
  "prednisolone",
  "prednisone",
  "pregabalin",
  "primaquine",
  "prochlorperazine",
  "proguanil",
  "propofol",
  "propranolol",
  "prucalopride",
  "pyrazinamide",
  "pyridostigmine",
  "pyrimethamine",
  "quinapril",
  "rabeprazole",
  "raltegravir",
  "ramipril",
  "ranitidine",
  "remdesivir",
  "remifentanil",
  "retigabine",
  "ribavirin",
  "rifaximin",
  "rilpivirine",
  "emtricitabine",
  "tenofovir alafenamide",
  "rilpivirine",
  "emtricitabine",
  "tenofovir-df",
  "roflumilast",
  "rosiglitazone",
  "salbutamol",
  "albuterol",
  "sarilumab",
  "selexipag",
  "hydrocortisone",
  "ibalizumab-uiyk",
  "ibuprofen",
  "iloprost",
  "imipenem",
  "cilastatin",
  "indacaterol",
  "infliximab",
  "insulin",
  "interferon beta",
  "ipratropium bromide",
  "isoflurane",
  "isoniazid",
  "kanamycin",
  "lacosamide",
  "lactulose",
  "lamivudine",
  "lamotrigine",
  "lansoprazole",
  "ledipasvir",
  "sofosbuvir",
  "lenalidomide",
  "levetiracetam",
  "carbidopa",
  "levodopa",
  "levofloxacin",
  "levonorgestrel",
  "levothyroxine",
  "linagliptin",
  "linezolid",
  "liraglutide",
  "lisinopril",
  "lithium",
  "lorazepam",
  "lormetazepam",
  "magnesium",
  "magnesium",
  "medroxyprogesterone",
  "mefenamic acid",
  "megestrol acetate",
  "melatonin",
  "memantine",
  "meropenem",
  "mesalazine",
  "mesalamine",
  "metformin",
  "methotrexate",
  "methyldopa",
  "methylprednisolone",
  "metoclopramide",
  "metolazone",
  "metoprolol",
  "metronidazole",
  "micafungin",
  "miconazole",
  "milnacipran",
  "molnupiravir",
  "mometasone",
  "montelukast",
  "moxifloxacin",
  "moxonidine",
  "nandrolone",
  "naproxen",
  "natalizumab",
  "nebivolol",
  "niclosamide",
  "nimesulide",
  "nitazoxanide",
  "nitrofurantoin",
  "nitrous oxide",
  "noradrenaline",
  "norepinephrine",
  "norelgestromin",
  "rilpivirine",
  "abacavir",
  "lamivudine",
  "dopamine",
  "doravirine",
  "doravirine",
  "lamivudine",
  "tenofovir-df",
  "doxycycline",
  "dronabinol",
  "drospirenone",
  "dulaglutide",
  "duloxetine",
  "dydrogesterone",
  "empagliflozin",
  "emtricitabine",
  "emtricitabine",
  "tenofovir alafenamide",
  "emtricitabine",
  "tenofovir-df",
  "enalapril",
  "enflurane",
  "enoxaparin",
  "entecavir",
  "ephedrine",
  "epoprostenol",
  "eprosartan",
  "ertapenem",
  "escitalopram",
  "esomeprazole",
  "estradiol",
  "ethambutol",
  "ethionamide",
  "etonogestrel",
  "etravirine",
  "evolocumab",
  "exenatide",
  "famotidine",
  "fampridine",
  "favipiravir",
  "fenofibrate",
  "finasteride",
  "fingolimod",
  "fish oils",
  "flucloxacillin",
  "fluconazole",
  "flucytosine",
  "fludrocortisone",
  "flunisolide",
  "fluocinolone",
  "fluphenazine",
  "fluticasone",
  "fluvastatin",
  "fluvoxamine",
  "folic acid",
  "fondaparinux",
  "formoterol",
  "fosinopril",
  "fostemsavir",
  "fulvestrant",
  "furosemide",
  "gabapentin",
  "gentamicin",
  "glatiramer acetate",
  "gliclazide",
  "glimepiride",
  "glipizide",
  "glycopyrronium bromide",
  "guaifenesin",
  "halothane",
  "heparin",
  "hydralazine",
  "hydrochlorothiazide",
  "carbidopa",
  "levodopa",
  "colesevelam",
  "colestyramine",
  "cholestyramine",
  "cyclophosphamide",
  "diphenhydramine",
  "drospirenone",
  "epirubicin",
  "lenacapavir",
  "macrogol",
  "polyethylene glycol 3350",
  "meclizine",
  "midodrine",
  "orphenadrine",
  "procyclidine",
  "sodium valproate",
  "valproate semisodium",
  "divalproex sodium",
  "aldesleukin",
  "apomorphine",
  "atazanavir alone",
  "belimumab",
  "benralizumab",
  "benserazide",
  "levodopa",
  "bicalutamide",
  "biperiden",
  "brimonidine",
  "brolucizumab",
  "calcium",
  "casirivimab",
  "imdevimab",
  "cefuroxime",
  "cemiplimab",
  "crizanlizumab",
  "daratumumab",
  "dicycloverine",
  "difluprednate",
  "docusate",
  "dupilumab",
  "durvalumab",
  "tenofovir-df",
  "eptinezumab",
  "erenumab",
  "etoricoxib",
  "febuxostat",
  "filgrastim",
  "fluorouracil",
  "5-fu",
  "fremanuzemab",
  "galcanezumab",
  "glucosamine",
  "glyceryl trinitrate",
  "nitroglycerin",
  "golimumab",
  "hydrocortisone",
  "inclisiran",
  "iodine",
  "ipilimumab",
  "iron",
  "ketorolac",
  "magnesium",
  "maribavir",
  "mepolizumab",
  "mercaptopurine",
  "methimazole",
  "methocarbamol",
  "minoxidil",
  "naltrexone",
  "omalizumab",
  "pancreatic enzymes",
  "creon",
  "pembrolizumab",
  "phentermine",
  "promethazine",
  "risedronate",
  "rivastigmine",
  "ropinirole",
  "rotigotine",
  "secukinumab",
  "ticlopidine",
  "travoprost",
  "triclabendazole",
  "trospium",
  "ursodeoxycholic acid",
  "ursodiol",
  "ustekinumab",
  "vedolizumab",
  "zoledronic acid",
  "binimetinib",
  "sofosbuvir",
  "velpatasvir",
  "perazine",
  "mirabegron",
  "anastrazole",
  "letrozole",
  "capmatinib",
  "vitamin a",
  "retinol",
  "vitamin b1",
  "thiamine",
  "vitamin b12",
  "cyanocobalamin",
  "vitamin b2",
  "riboflavin",
  "vitamin b3",
  "niacin",
  "nicotinic acid",
  "vitamin b6",
  "pyridoxine",
  "vitamin b7",
  "biotin",
  "vitamin c",
  "ascorbic acid",
  "vitamin d2",
  "ergocalciferol",
  "vitamin d3",
  "colecalciferol",
  "cholecalciferol",
  "vitamin e",
  "tocopherol",
  "vitamin k",
  "phytomenadione",
  "zinc",
  "zanamivir",
  "trastuzumab",
  "trametinib",
  "telbivudine",
  "tecovirimat",
  "sumatriptan",
  "sotalol",
  "rizatriptan",
  "rituximab",
  "rimantadine",
  "pilocarpine",
  "pertuzumab",
  "pemetrexed",
  "nicotinamide",
  "niacinamide",
  "necitumumab",
  "naratriptan",
  "multivitamins",
  "meloxicam",
  "letermovir",
  "iron",
  "hydroxycarbamide",
  "hydroxyurea",
  "ganciclovir",
  "frovatriptan",
  "foscarnet",
  "ferrous sulfate",
  "ferrous fumarate",
  "famciclovir",
  "exemestane",
  "tenofovir alafenamide",
  "emtricitabine",
  "tenofovir-df",
  "dexmethylphenidate",
  "methylphenidate",
  "dacomitinib",
  "cidofovir",
  "bumetanide",
  "benzonatate",
  "benzatropine",
  "benztropine",
  "baloxavir",
  "amivantamab",
  "amantadine",
  "alpelisib",
  "adefovir",
  "abrocitinib",
  "nicorandil",
  "tenofovir alafenamide",
  "zopiclone",
  "tranylcypromine",
  "tiagabine",
  "sulfasalazine",
  "sacubitril",
  "rocuronium",
  "loperamide",
  "ivermectin",
  "indapamide",
  "imatinib",
  "hydromorphone",
  "haloperidol",
  "granisetron",
  "flunitrazepam",
  "nabumetone",
  "albuvirtide",
  "aminophylline",
  "amitriptyline",
  "artemether",
  "artesunate",
  "buprenorphine",
  "bupropion",
  "cannabis",
  "chlorpromazine",
  "clindamycin",
  "clomipramine",
  "codeine",
  "cyclobenzaprine",
  "desipramine",
  "donepezil",
  "doxepin",
  "efavirenz",
  "eltrombopag",
  "eslicarbazepine",
  "ethinylestradiol",
  "ezetimibe",
  "fexofenadine",
  "fluoxetine",
  "gemfibrozil",
  "gestodene",
  "griseofulvin",
  "hydroxychloroquine",
  "imipramine",
  "irbesartan",
  "isosorbide dinitrate",
  "levomepromazine",
  "loratadine",
  "losartan",
  "maprotiline",
  "methadone",
  "mianserin",
  "mirtazapine",
  "modafinil",
  "mycophenolate",
  "nevirapine",
  "norgestimate",
  "nortriptyline",
  "oxcarbazepine",
  "paliperidone",
  "paroxetine",
  "perphenazine",
  "pioglitazone",
  "pirfenidone",
  "rufinamide",
  "siponimod",
  "sotorasib",
  "tamoxifen",
  "theophylline",
  "torasemide",
  "trimipramine",
  "valproic acid",
  "valproate",
  "venlafaxine",
  "vortioxetine",
  "abacavir",
  "abiraterone",
  "acarbose",
  "acetylcysteine",
  "aciclovir",
  "aclidinium bromide",
  "adalimumab",
  "adrenaline",
  "epinephrine",
  "agomelatine",
  "alcohol",
  "alcuronium",
  "alectinib",
  "alemtuzumab",
  "alendronic acid",
  "allopurinol",
  "ambrisentan",
  "amikacin",
  "amiloride",
  "amisulpride",
  "amoxicillin",
  "amphotericin b",
  "ampicillin",
  "anakinra",
  "anidulafungin",
  "antacids",
  "anti-thymocyte globulin",
  "argatroban",
  "asenapine",
  "aspirin",
  "atenolol",
  "atezolizumab",
  "atovaquone",
  "azathioprine",
  "azithromycin",
  "baclofen",
  "bamlanivimab",
  "etesevimab",
  "baricitinib",
  "basiliximab",
  "bebtelovimab",
  "beclometasone",
  "belatacept",
  "benazepril",
  "bendroflumethiazide",
  "betamethasone",
  "bezafibrate",
  "bictegravir",
  "emtricitabine",
  "tenofovir alafenamide",
  "bisacodyl",
  "bisoprolol",
  "brivaracetam",
  "bromazepam",
  "budesonide",
  "cabotegravir",
  "cabotegravir",
  "rilpivirine",
  "calcium",
  "canagliflozin",
  "canakinumab",
  "candesartan",
  "capecitabine",
  "capreomycin",
  "captopril",
  "carbocisteine",
  "carvedilol",
  "casirivimab",
  "imdevimab",
  "caspofungin",
  "cefalexin",
  "cefazolin",
  "cefepime",
  "cefixime",
  "cefotaxime",
  "ceftazidime",
  "ceftriaxone",
  "celecoxib",
  "cetirizine",
  "chloramphenicol",
  "chlortalidone",
  "ciclesonide",
  "cilazapril",
  "cimetidine",
  "ciprofloxacin",
  "cisatracurium",
  "citalopram",
  "clavulanic acid",
  "clobetasol",
  "clofazimine",
  "clofibrate",
  "clonidine",
  "cloxacillin",
  "convalescent plasma",
  "covid-19 vaccines",
  "cyclizine",
  "cycloserine",
  "dalteparin",
  "dantrolene sodium",
  "dapagliflozin",
  "dapsone",
  "desflurane",
  "desogestrel",
  "dexamethasone",
  "dexmedetomidine",
  "dextromethorphan",
  "diclofenac",
  "dimethyl fumarate",
  "dipyridamole",
  "dobutamine",
  "dolasetron",
  "dolutegravir",
  "lamivudine",
  "semaglutide",
  "senna",
  "sertraline",
  "sevoflurane",
  "sitagliptin",
  "sodium nitroprusside",
  "sofosbuvir",
  "sofosbuvir",
  "velpatasvir",
  "sotrovimab",
  "spectinomycin",
  "spironolactone",
  "stanozolol",
  "streptokinase",
  "streptomycin",
  "sulfadiazine",
  "sulfadoxine",
  "sulpiride",
  "suxamethonium",
  "succinylcholine",
  "tapentadol",
  "tazobactam",
  "telmisartan",
  "temazepam",
  "tenofovir-df",
  "terbinafine",
  "teriflunomide",
  "testosterone",
  "tetracaine",
  "tetracyclines",
  "thiopental",
  "tiapride",
  "timolol",
  "tinidazole",
  "tinzaparin",
  "tiotropium bromide",
  "tixagevimab",
  "cilgavimab",
  "tizanidine",
  "tocilizumab",
  "tolbutamide",
  "topiramate",
  "trandolapril",
  "treprostinil",
  "trimethoprim",
  "sulfamethoxazole",
  "ulipristal",
  "umeclidinium bromide",
  "valaciclovir",
  "valacyclovir",
  "vancomycin",
  "vasopressin",
  "vecuronium",
  "vigabatrin",
  "vilanterol",
  "vildagliptin",
  "xipamide",
  "zaleplon",
  "zidovudine",
  "zonisamide",
  "carbimazole",
  "etanercept",
  "leflunomide",
  "ozanimod"
];
export const safe2: string[] = [
  "biktarvy",
  "dovato",
  "juluca",
  "triumeq",
  "delstrigo",
  "odefsey",
  "prochlorperazine"
];
export const DICT: Record<string, string> = {
  "alprazolam": "{若不喘沒呼吸抑制疑慮可考慮改成沒交互作用的口服ativan}此藥藥效會變強2-5倍,故減量或停用到吃完Paxlovid的3天後",
  "gestodene": "影嚮小,維持原劑量",
  "norgestimate": "影嚮小,維持原劑量",
  "saxagliptin": "併用 Paxlovid 時,需減量成每天僅 2.5mg",
  "clopidogrel": "此藥藥效變弱,故無需停藥,但若近6週內剛放支架,建議換Molnupiravir或先跟心臟科討論",
  "labetalol": "此藥藥效變弱,故無需停藥",
  "pioglitazone": "此藥藥效會變強一點,可先維持原劑量",
  "glibenclamide": "此藥藥效會變強,故需減量和密切測血糖以免低血糖",
  "glyburide": "此藥藥效會變強,故需減量和密切測血糖以免低血糖",
  "repaglinide": "此藥藥效會變強,故需減量和密切測血糖以免低血糖",
  "dabigatran": "此藥藥效會變強,故最多早晚各110mg,若腎功能異常則早晚各75mg",
  "tamsulosin": "此藥藥效會變強,故每天勿超過0.4mg和小心低血壓",
  "edoxaban": "此藥藥效會變強,故每天30mg勿更高",
  "diltiazem": "此藥藥效會變強,故吃前需先測心跳血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "verapamil": "此藥藥效會變強,故吃前需先測心跳血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "amlodipine": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "felodipine": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "nicardipine": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "nifedipine": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "nisoldipine": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "nitrendipine": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "nimodipine": "此藥藥效會變強,若巳吃超過7天就可併用,只是吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半)",
  "doxazosin": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "valsartan": "此藥藥效會變強,故吃前需先測血壓(比平常高就原劑量,比平常低就暫不吃;跟平常一樣則劑量減半,例如吃一次停一次)",
  "warfarin": "此藥藥效會變強,故需測INR以過高時停此藥",
  "chlordiazepoxide": "此藥藥效會變強,建議減量和吃前注意是否有疑似過量之症狀(看藥袋上的副作用,有就需暫時停用)",
  "nateglinide": "此藥藥效可能會變強,故需密切測血糖以免低血糖",
  "budesonide": "此藥會變強很多而不宜併用,只有吸入型可安全併用",
  "diamorphine": "此藥會變強,留意opiate toxicity",
  "lsd": "此藥會變強,留意LSD toxicity",
  "lysergic acid diethylamide": "此藥會變強,留意LSD toxicity",
  "lidocaine": "此藥會變強,建議追蹤血中濃度",
  "ghb": "此藥therapeutic range窄而易被Paxlovid加強超出安全範圍,盡量避免併用",
  "gamma-hydroxybutyrate": "此藥therapeutic range窄而易被Paxlovid加強超出安全範圍,盡量避免併用",
  "atorvastatin": "先停用或改成每兩天吃10mg",
  "rosuvastatin": "先停用或改成每兩天吃10mg",
  "dexamethasone": "6mg/day可原劑量給,較高劑量如16mg/day會使Paxlovid藥效變弱而建議改成prednisolone",
  "digoxin": "此藥劑量減半(變半顆 或 吃一次停一次)",
  "acalabrutinib": "臺灣血液腫瘤藥學會建議可先停此藥到吃完Paxlovid的48小時後",
  "alfuzosin": "{禁忌症，此藥濃度會大幅上升，可能會出現嚴重低血壓，建議停用並於Paxlovid療程結束第三天再恢復使用。}此藥藥效會大幅增強，建議可由醫師評估暫時停用，並於Paxlovid療程結束第三天再恢復使用。",
  "aliskiren": "{不建議併用，此藥濃度會大幅上升，可能會出現低血壓。}此藥藥效會大幅增強，建議可由醫師評估暫時停用。",
  "amiodarone": "{禁忌症，此藥濃度會大幅上升，可能會出現心律不整，且此藥物半衰期較長，建議改用其他COVID-19抗病毒藥物。}此藥藥效會大幅增強，建議可由醫師評估改用其他COVID-19抗病毒藥物。",
  "apalutamide": "{臺灣血液腫瘤藥學會建議勿用Paxlovid（改用別的抗病毒藥）}",
  "apixaban": "不宜停則上限是早晚各2.5mg,paxlovid吃完3天後才可復正常劑量",
  "bepridil": "{禁忌症，此藥濃度會大幅上升，建議停用此藥至少36小時後方可使用Paxlovid。}此藥藥效會大幅增強，建議可由醫師評估改用其他COVID-19抗病毒藥物。",
  "bosentan": "{不建議併用，此藥濃度會大幅上升，可能會出現低血壓。}此藥藥效會增強，建議可由醫師評估停用此藥至少36小時後方可使用Paxlovid。",
  "bosutinib": "{不建議併用，此藥濃度會大幅上升，建議停用至少24小時並於Paxlovid療程結束第三天再恢復使用。}此藥藥效會增強，建議可由醫師評估停用此藥至少24小時後方可使用Paxlovid，並於Paxlovid療程結束第三天再恢復使用。",
  "carbamazepine": "{禁忌症，Paxlovid濃度會大幅下降，建議改用其他COVID-19抗病毒藥物。}此藥會降低Paxlovid藥效，建議可由醫師評估改用其他COVID-19抗病毒藥物。",
  "carfentanil": "{不建議併用，此藥濃度會大幅上升，可能會出現呼吸抑制的副作用。}此藥藥效會大幅增強，建議可由醫師評估暫時停用。",
  "ciclosporin": "{不建議併用，此藥濃度會大幅上升，建議減低劑量並密集監測藥物血中濃度，或改用其他COVID-19抗病毒藥物。}此藥藥效會大幅增強，建議可由醫師評估減低劑量並密集監測藥物血中濃度，另可由醫師評估考慮改用其他COVID-19抗病毒藥物。",
  "cyclosporine": "{不建議併用，此藥濃度會大幅上升，建議減低劑量並密集監測藥物血中濃度，或改用其他COVID-19抗病毒藥物。}此藥藥效會大幅增強，建議可由醫師評估減低劑量並密集監測藥物血中濃度，另可由醫師評估考慮改用其他COVID-19抗病毒藥物。",
  "cisapride": "{禁忌症，此藥濃度會大幅上升，可能會出現心律不整。}此藥藥效會大幅增強，建議可由醫師評估暫時停用。",
  "clonazepam": "{如需併用，須注意此藥的副作用（鎮靜、困惑），並視狀況調降此藥劑量。}此藥藥效會大幅增強，建議可由醫師評估暫時停用，並於 Paxlovid 療程結束第三天再恢復使用。",
  "clozapine": "{如需併用，可能會出現危及生命的心律不整。}此藥藥效會大幅增強，建議暫時停用，或改用其他抗病毒藥物。",
  "colchicine": "{禁忌症，此藥濃度會大幅上升，可能會出現colchicine毒性，建議暫時停用或減低劑量。}此藥藥效會大幅增強，建議可由醫師評估暫時停用或減低劑量。",
  "dextropropoxyphene": "{不建議併用，此藥濃度會大幅上升，可能會出現心律不整的副作用。}此藥藥效會大幅增強，建議可由醫師評估改用其他COVID-19抗病毒藥物。",
  "diazepam": "{如需併用，須注意此藥的副作用（鎮靜、困惑），並視狀況調降此藥劑量。}此藥藥效會增強，建議可由醫師評估減低劑量，並於 Paxlovid 療程結束第三天再恢復原本使用。",
  "dihydroergotamine": "{禁忌症，此藥濃度會大幅上升，可能會出現血管痙攣、缺血。}Ergot 併用 Paxlovid 恐會產生危及生命之血管痙攣，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "disopyramide": "{禁忌症，disopyramide濃度會大幅上升。}disopyramide藥效會大幅增強，請依醫師指示暫時停用或減低劑量。",
  "dofetilide": "{禁忌症，dofetilide濃度會大幅上升。}dofetilide藥效會大幅增強，請依醫師指示暫時停用或減低劑量。",
  "domperidone": "{禁忌症，domperidone濃度會大幅上升。}domperidone藥效會大幅增強，請依醫師指示暫時停用或減低劑量。",
  "dronedarone": "{禁忌症，dronedarone濃度會大幅上升。}dronedaronep藥效會大幅增強，請依醫師指示暫時停用。",
  "Dapoxetine": "{禁忌症，dapoxetine濃度會大幅上升。}dapoxetine藥效會大幅增強，請依醫師指示暫時停用。",
  "elbasvir": "{不建議併用，濃度會大幅上升，可能會ALT上升，建議停用並於Paxlovid療程結束第三天再恢復使用，然而需考慮是否一定要使用Paxilovid，因為停用此藥可能會增加HCV治療失敗風險}",
  "grazoprevir": "{禁忌症，濃度會大幅上升，可能會ALT上升，建議停用並於Paxlovid療程結束第三天再恢復使用，然而需考慮是否一定要使用Paxilovid，因為停用此藥可能會增加HCV治療失敗風險}",
  "enzalutamide": "{臺灣血液腫瘤藥學會建議勿用Paxlovid（改用別的抗病毒藥）}",
  "eplerenone": "{禁忌症，eplerenone濃度會大幅上升。}eplerenone藥效會大幅增強，請依醫師指示暫時停用。",
  "ergometrine": "{禁忌症，濃度會大幅上升，可能會增加此藥物副作用（四肢缺血、昏迷、甚至死亡），建議停用}Ergot 併用 Paxlovid 恐會產生危及生命之血管痙攣，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "ergonovine": "{禁忌症，濃度會大幅上升，可能會增加此藥物副作用（四肢缺血、血管痙攣），建議停用}Ergot 併用 Paxlovid 恐會產生危及生命之血管痙攣，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "ergotamine": "{禁忌症，濃度會大幅上升，可能會增加此藥物副作用（四肢缺血、昏迷、甚至死亡），建議停用}Ergot 併用 Paxlovid 恐會產生危及生命之血管痙攣，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "estazolam": "{如需併用，須注意此藥的副作用（鎮靜、困惑），並視狀況調降此藥劑量。}此藥藥效會增強，建議可由醫師評估暫時停用或減低劑量，並於 Paxlovid 療程結束第三天再恢復使用。",
  "everolimus": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "flecainide": "{禁忌症，flecainide濃度會大幅上升，可能會出現心律不整}flecainide藥效會大幅增強，請依醫師指示暫時停用 ",
  "flurazepam": "{禁忌症，可能會出現鎮靜、困惑，建議暫停使用並於 Paxlovid 療程結束第三天再恢復使用}flurazepam藥效會大幅增強，請依醫師指示暫時停用或減低劑量，並於 Paxlovid 療程結束第三天再恢復原本使用。",
  "glecaprevir": "{不建議併用，濃度會大幅上升，可能會ALT上升，建議停用並於Paxlovid療程結束第三天再恢復使用，然而需考慮是否一定要使用Paxilovid，因為停用此藥可能會增加HCV治療失敗風險}",
  "pibrentasvir": "{不建議併用，濃度會大幅上升，可能會ALT上升，建議停用並於Paxlovid療程結束第三天再恢復使用，然而需考慮是否一定要使用Paxilovid，因為停用此藥可能會增加HCV治療失敗風險}",
  "halofantrine": "{禁忌症，halofantrine濃度會大幅上升，建議更換其他covid-19抗病毒藥物治療}halofantrine藥效會大幅增強，建議可由醫師評估暫時停用。",
  "ibrutinib": "臺灣血液腫瘤藥學會建議可先停此藥到吃完Paxlovid的48小時後",
  "ivabradine": "{禁忌症，併用後ivabradine濃度會大幅上升，增加QTc prolong風險。}ivabradine藥效會大幅增強，請依醫師指示暫時停用。",
  "ivosidenib": "{臺灣血液腫瘤藥學會建議勿用Paxlovid（改用別的抗病毒藥）}",
  "lercanidipine": "此藥藥效會大幅增強故不可併用，請依醫師指示暫時替換為其他降血壓藥。",
  "lovastatin": "{Lovastatin 濃度會因 Paxlovid 而增加 100 倍，請強調停用 lovastatin 12 小時後，再開始使用 Paxlovid。於 Paxlovid 治療完畢 3-5 天後，再加回 Paxlovid。}lovastatin藥效會大幅增強。請於停用 lovastatin 後 12 小時再開始使用 Paxlovid，並於 Paxlovid 療程結束後 3-5 天再恢復lovastatin使用。",
  "lumateperone": "{應避免併用}lumateperone藥效會大幅增強，請依醫師指示暫時停用。",
  "lurasidone": "{如需併用，可能會出現危及生命的心律不整。}lurasidone藥效會大幅增強，建議暫時停用，或改用其他抗病毒藥物。",
  "methylergometrine": "{0}Ergot 併用 Paxlovid 恐會產生危及生命之血管痙攣，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "methylergonovine": "{0}Ergot 併用 Paxlovid 恐會產生危及生命之血管痙攣，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "midazolam": "{如需併用，須注意此藥的副作用（鎮靜、呼吸抑制），並視狀況調降此藥劑量。}此藥藥效會增強，建議可由醫師評估暫時停用或減低劑量，並於 Paxlovid 療程結束第三天再恢復使用。",
  "midostaurin": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "neratinib": "臺灣血液腫瘤藥學會建議可先停此藥到吃完Paxlovid的48小時後",
  "pethidine": "{禁忌症，pethidine併用Paxlovid可能會造成呼吸抑制、中樞抑制等毒性反應。建議改用其他止痛藥物。}Pethidine濃度會大幅增強，建議依醫師建議換成其他止痛藥物。",
  "meperidine": "{禁忌症，meperidine併用Paxlovid可能會造成呼吸抑制、中樞抑制等毒性反應。建議改用其他止痛藥物。}Meperidine濃度會大幅增強，建議依醫師建議換成其他止痛藥物。",
  "pimozide": "{禁忌症}pimozid併用 Paxlovid 恐會產生危及生命之心律異常，難以評估停用多久後方為安全，建議轉為 \"停藥也來不及\"，直接換用其他抗病毒藥",
  "propafenone": "{禁忌症，如需併用，可能會出現危及生命的心律不整。}propafenone藥效會大幅增強，請依醫師指示暫時停用。",
  "quetiapine": "{文獻上如需併用，建議使用1/6的劑量，直到PAXLOVID停藥3天後}quetiapine藥效會大幅增強，請依醫師指示暫時停用或減低劑量，並於 Paxlovid 療程結束第三天再恢復原本使用。",
  "quinidine": "{禁忌症，如需併用，可能會出現危及生命的心律不整。}quinidine藥效會大幅增強，請依醫師指示暫時停用。",
  "ranolazine": "{禁忌症，如需併用，可能會出現危及生命的心律不整。}ranolazine藥效會大幅增強，請依醫師指示暫時停用。",
  "rifampicin": "{建議改用其他抗病毒藥物，如無法替代，則將rifampin改為rifabutin}",
  "rifapentine": "{建議改用其他抗病毒藥物。}",
  "rivaroxaban": "{如治療AF且無法改用其他抗病毒藥物，建議改用edoxaban 減半劑量或dabigatran}rivaroxaban藥效會大幅增強，請依醫師指示改用其他抗凝血藥物，並注意出血/栓塞症狀。",
  "salmeterol": "{禁忌症，可能會出現危及生命的心律不整，建議暫停使用並於 Paxlovid 療程結束第三天再恢復使用或改用formoterol成分的吸入劑，或改用其他抗病毒藥物。}salmeterol藥效會大幅增強，請依醫師指示改用其他吸入劑，或改用其他抗病毒藥物。",
  "sildenafil": "{如需併用，須注意此藥的副作用（低血壓、暈厥），並降低劑量（48小時內不超過25mg）。}sildenafil藥效會增強，請依醫師指示暫時停用或減低劑量，並於 Paxlovid 療程結束第三天再恢復使用。",
  "simvastatin": "{禁忌症，simvastatin濃度會大幅上升，請依醫師指示停用 12小時後方可使用Paxlovid ，並於 Paxlovid 療程結束第三天再恢復使用。}simvastatin藥效會大幅增強，請依醫師指示停用12小時後方可使用Paxlovid ，並於 Paxlovid 療程結束第三天再恢復使用。",
  "sirolimus": "{建議停用48小時後，方可使用Paxlovid，並於完成Paxlovid療程後第3-7天恢復使用（依照藥物監測濃度），或改用其他抗病毒藥物。}sirolimus藥效會大幅增強，請依醫師指示停用48小時後方可使用Paxlovid ，並於 Paxlovid 療程結束依照醫囑恢復使用。",
  "st john's wort": "{建議暫停使用st john＇s wort}請依醫師指示暫停使用st john＇s wort",
  "tacrolimus": "{建議停用24小時後，方可使用Paxlovid，並於完成Paxlovid療程後第3-7天恢復使用（依照藥物監測濃度），或改用其他抗病毒藥物。}tacrolimus藥效會大幅增強，請依醫師指示停用24小時後方可使用Paxlovid ，並於 Paxlovid 療程結束依照醫囑恢復使用。",
  "tadalafil": "{如需併用，須注意此藥的副作用（低血壓、暈厥），停用24小時後方可使用Paxlovid，並於 Paxlovid 療程結束第7天再恢復使用 (由20mg開始) 或 改用其他抗病毒藥物。}tadalafil藥效會增強，請依醫師指示停用24小時後方可使用Paxlovid，並於 Paxlovid 療程結束第7天再恢復使用。",
  "ticagrelor": "{禁忌症，濃度會大幅上升，建議改用prasugrel(可等Ticagrelor原本該吃的時間,改成prasugrel 5mg 4# PO ST then 3.75mg QD * 6 days)，或改用其他抗病毒藥物。}ticagrelor藥效會增強，請依醫師指示改用其他藥物，並注意出血/栓塞症狀。",
  "triazolam": "{如併用，此藥濃度會增加4-22倍，可能增加副作用（鎮靜、呼吸抑制），建議暫停使用triazolam，或改用其他抗病毒藥物。}triazolam藥效會大幅增強，請依醫師指示暫停使用或改用其他藥物。",
  "venetoclax": "{臺灣血液腫瘤藥學會建議CLL/SLL: ramp-up phase, no Paxlovid®; maintenance phase, reduce to 100 mg QD; AML: Ramp-up phase: 10 mg on day 1, 20 mg on day 2, 50 mg on day 3, and 100 mg on day 4; maintenance phase: reduce to 100 mg QD}",
  "avapritinib": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "crizotinib": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "dabrafenib": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "mitotane": "{臺灣血液腫瘤藥學會建議勿用Paxlovid（改用別的抗病毒藥）}",
  "tazemetostat": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "tepotinib": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "topotecan": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "vemurafenib": "臺灣血液腫瘤藥學會建議若無法改Paxlovid成別的抗病毒藥，可先停此藥到吃完Paxlovid的48小時後",
  "cobimetinib": "臺灣血液腫瘤藥學會建議可先停此藥到吃完Paxlovid的48小時後",
  "gilteritinib": "{建議改用其他抗病毒藥物，如需併用請降低gilteritinib的劑量，並審慎追蹤不良反應。}gilteritinib藥效會增強，請依醫師指示暫時停用，或審慎監測相關不良反應。",
  "regorafenib": "臺灣血液腫瘤藥學會建議可先停此藥到吃完Paxlovid的48小時後",
  "abemaciclib": "abemaciclib藥效會增強，建議可由醫師評估暫時停用或減低劑量，並於 Paxlovid 療程結束第三天再恢復使用。",
  "afatinib": "afatinib藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束依照醫囑恢復使用。",
  "axitinib": "{臺灣血液腫瘤藥學會建議Reduce by 50%}",
  "brigatinib": "{brigatinib藥效可能會增強，建議併用Paxlovid期間將brigatinib劑量減半使用，並監測毒性，於 Paxlovid 療程結束 3 天後恢復原劑量服用。}brigatinib藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束3天後，依照醫囑恢復使用。",
  "cabozantinib": "{臺灣血液腫瘤藥學會建議Reduce by 20 mg (tablet)}",
  "ceritinib": "{ceritinib藥效會增強，請考慮使用其他抗病毒藥物，如需併用期間減少1/3的劑量，並於Paxlovid停用後，調回劑量。}ceritinib藥效會增強，請依醫師指示減低劑量，並於Paxlovid停用後，恢復原本使用。",
  "dasatinib": "{建議改用其他抗病毒藥物，如需併用請減低dasatinib劑量從70-100mg/day to 20mg/day 或 140mg/day to 40mg/day，並注意QTc prolong。}請依醫師指示減低dasatinib劑量。",
  "entrectinib": "{臺灣血液腫瘤藥學會建議Reduce to 100 mg QD}",
  "erlotinib": "{erlotinib濃度會大幅增加。如需併用，建議降低erlotinib劑量（可減半使用）。}請依醫師指示使用或減低劑量。",
  "lapatinib": "{Lapatinib藥效會被增強，請將 lapatinib 日劑量從 1250 mg 降至 500 mg，並於 Paxlovid 療程結束 7 天後再恢復原劑量。}",
  "larotrectinib": "{臺灣血液腫瘤藥學會建議Reduce by 50%}",
  "lorlatinib": "{臺灣血液腫瘤藥學會建議Reduce the starting dose to 75 mg QD; Already on 75 mg QD, reduce to 50 mg QD}",
  "nilotinib": "{nilotinib濃度可能會因此上升，建議調降nilotinib劑量，待Paxlovid療程結束後，視狀況逐步調整回原先劑量}請依醫師指示使用或減低劑量。",
  "olaparib": "{olaparib濃度可能會因此上升，建議調降olaparib劑量}請依醫師指示使用或減低劑量。",
  "palbociclib": "{palbociclib濃度可能會因此上升，建議調降palbociclib劑量，待Paxlovid療程結束後，視狀況逐步調整回原先劑量}請依醫師指示使用或減低劑量。",
  "panobinostat": "{臺灣血液腫瘤藥學會建議Reduce to 10 mg QD}",
  "pazopanib": "{pazopanib濃度可能會因此上升，且可能會增加QT prolongation的風險。建議調降pazopanib劑量，並監測病人用藥之不良反應}請依醫師指示使用或減低劑量。",
  "ponatinib": "{若病人目前每天使用ponatinib劑量為10mg，請考慮改用其他抗病毒藥物，若非上述劑量而需併用Paxlovid，則減低ponatinib劑量（每天45mg 改為30mg，30mg 改為15mg，15mg 改為10mg），並於Paxlovid停藥3-5天後，將ponatinib調回原劑量}請依照醫師指示減低劑量，並於Paxlovid停藥3-5天後，將ponatinib調回原劑量",
  "ribociclib": "{ribociclib濃度可能會因此上升，且可能會增加QT prolongation的風險。建議調降ribociclib劑量，待Paxlovid療程結束後，視狀況逐步調整回原先劑量，並監測病人EEG}請依醫師指示使用或減低劑量。",
  "ruxolitinib": "{不建議併用, acute GVHD不需要調整劑量，其他適應症建議減低ruxolitinib 50%劑量}ruxolitinib藥效會增強，請依醫師指示之劑量使用。",
  "selpercatinib": "{建議停藥, 並於Paxlovid療程結束第三天後再使用selpercatinib/替代方式為調整selpercatinib劑量(120mg bid調整為40mg bid或160mg bid調整為80mg bid並監測毒性)}請依照醫師指示減低劑量或停藥，並於Paxlovid停藥3天後，再調整或加回selpercatinib原劑量",
  "sunitinib": "{併用於GIST或advanced RCC時建議減低劑量至37.5mg qd，併用於 pancreatic neuroendocrine tumors建議減低劑量至25mg qd}sunitinib藥效會增強，請依醫師指示之劑量使用。",
  "tirabrutinib": "{臺灣血液腫瘤藥學會建議Reduce to 320 mg QD}",
  "alfentanil": "{alfentanil藥效會增強，可能會增加呼吸抑制效果，請於併用期間減低劑量，並於Paxlovid停用後，逐步調回劑量。}針劑劑型，病人不會自行使用，無需衛教。",
  "alosetron": "alosetron藥效會增強，請依醫師指示減低劑量 ，並注意是否有腸胃道不適，如腹痛、噁心、嘔吐。",
  "aripiprazole": "{aripiprazole藥效會增強，可能會增加QTc prolong，請考慮使用其他抗病毒藥物，如需併用期間減半劑量。}aripiprazole藥效會增強，請依醫師指示減半使用。",
  "brexpiprazole": "brexpiprazole藥效會增強，請依醫師指示減半使用。",
  "bupivacaine": "{bupivacaine濃度可能會增加，仍可使用。}針劑劑型，病人不會自行使用，無需衛教。",
  "buspirone": "{buspirone藥效會增強，可依病情減低劑量 ，並注意是否有呼吸抑制、EPS。}buspirone藥效會增強，請依醫師指示減低劑量 ，並注意是否有呼吸困難、手腳顫抖。",
  "cladribine": "{建議改用其他抗病毒藥物，如需併用請與Paxlovid間隔至少3小時。}請依醫師指示，與Paxlovid間隔至少3小時。",
  "clarithromycin": "{建議改用其他抗病毒藥物，如需併用請減低clarithromycin劑量50-75%，並注意QTc prolong。}clarithromycin藥效會增強，請依醫師指示減低劑量。",
  "clobazam": "{短期併用較不會顯著影響，視狀況調降此藥劑量，並注意此藥的副作用（鎮靜、困惑）。}請依醫師指示使用或減低劑量。",
  "erythromycin": "{erythromycin濃度會大幅增加，並增加QT prolongation的風險。如非必要，可暫時停用 erythromycin。如需併用，可調降erythromycin劑量，並於使用 Paxlovid 期間與停藥後三天，監測心律。}erythromycin藥效會增強，請依醫師指示暫時停用，或調降劑量並審慎監測心律狀況。",
  "ethosuximide": "{台灣沒有上市}台灣沒有上市，無須衛教",
  "fosaprepitant": "{fosaprepitant濃度會增加數倍，不建議併用。如需併用，請監測不良反應。}針劑劑型，病人不會自行使用，無需衛教。",
  "hydrocodone": "{hydrocodone濃度會顯著上升，建議先將hydrocodone劑量減半使用，待Paxlovid療程結束後，視疼痛狀況逐步調整回原先劑量。}hydrocodone藥效會增強，請依醫師指示調降劑量，並於抗病毒藥療程結束後，視疼痛控制狀況逐步恢復hydrocodone劑量。",
  "hydroxyzine": "{可能會增加QT prolongation的風險。如非必要，可暫時停用 hydroxyzine。如需並用，請於使用 Paxlovid 期間與停藥後三天，監測心律。}請依醫師指示調降劑量或暫時停用，並審慎監測心律狀況。",
  "iloperidone": "{iloperidone濃度會大幅增加。請將iloperidone劑量減半使用，並於療程結束後恢復原劑量。}請依醫師指示使用或減低劑量。",
  "itraconazole": "{如需併用，itraconazole劑量不得超過200mg/day。}請依醫師指示使用或減低劑量。",
  "ketamine": "{醫療級ketamine為針劑劑型，病人不會自行使用}針劑劑型，病人不會自行使用，無需衛教。",
  "ketoconazole": "{目前已無ketoconazole systemic 劑型，外用軟膏劑型理論上無顯著影響}",
  "lacidipine": "{lacidipine濃度可能會因此上升，建議依病人血壓狀況調降劑量。}請依醫師指示使用或減低劑量。",
  "tramadol": "{tramadol藥效會增強，併用時建議減低tramadol劑量，並注意呼吸抑制.癲癇.serotonin syndrome等副作用。}tramadol藥效會增強，請依醫師指示減低劑量使用。",
  "trazodone": "{trazodone藥效會增強，不建議併用，會增加QT prolong風險。}trazodone藥效會增強，請依醫師指示減低劑量使用。",
  "vinblastine": "{vinblasteine藥效會增強，不建議併用，會增加血液/腸胃道副作用}vinblastine藥效會增強，請依醫師指示之劑量使用。",
  "vincristine": "{vincristine藥效會增強，不建議併用，會增加血液/腸胃道副作用}vincristine藥效會增強，請依醫師指示之劑量使用。",
  "zolpidem": "{zolpidem藥效會增加, 併用時建議降低zolpidem劑量}zolpidem藥效會增強，請依醫師指示降低劑量使用。",
  "zotepine": "{zotepine藥效會增加, 併用時建議降低zotepine劑量, paxilovid停藥後3天可恢復}zotepine藥效會增強，請依醫師指示降低劑量使用。",
  "hydroxyChloroquine": "{沒QTc prolonged才可併用}",
  "almotriptan": "{almotriptan藥效會增強，建議併用期間起始劑量降低為6.25mg，極量不得超過12.5mg（肝腎功能障礙者，不建議併用），並於Paxlovid停用3天後，逐步調回劑量。}almotriptan藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束後依照醫囑恢復使用。",
  "atomoxetine": "{atomoxetine藥效可能會增強，建議併用期間監測相關不良反應：如高血壓、噁心、思睡}almotriptan藥效會增強，請監測相關不良反應（如高血壓、噁心、思睡等）。",
  "brincidofovir": "{為避免影響彼此藥物濃度，建議於 brincidofovir 服藥後至少 3 小時，再服用 Paxlovid。併用請監測相關不良反應（腹瀉、腸胃道症狀）}為避免影響彼此藥物濃度，建議於 brincidofovir 服藥後至少 3 小時，再服用 Paxlovid。併用請監測相關不良反應（腹瀉、腸胃道症狀）",
  "cilostazol": "{cilostazol藥效可能會增強，建議併用期間將cilostazol劑量減半，監測相關出血或栓塞徵象，並於Paxlovid療程結束3天後，再恢復cilostazol原劑量服用。}cilostazol藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束3天後，再依照醫囑恢復原劑量使用。",
  "ivacaftor": "{Elexacaftor/tezacaftor/ivacaftor藥效會增強，建議在開始併用Paxlovid的第一天與第五天服用Elexacaftor/tezacaftor/ivacaftor，並於療程結束4天後，恢復Elexacaftor/tezacaftor/ivacaftor原有劑量服用。}Elexacaftor/tezacaftor/ivacaftor藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束4天後，依照醫囑恢復使用。",
  "tezacaftor": "{Elexacaftor/tezacaftor/ivacaftor藥效會增強，建議在開始併用Paxlovid的第一天與第五天服用Elexacaftor/tezacaftor/ivacaftor，並於療程結束4天後，恢復Elexacaftor/tezacaftor/ivacaftor原有劑量服用。}Elexacaftor/tezacaftor/ivacaftor藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束4天後，依照醫囑恢復使用。",
  "elexacaftor": "{Elexacaftor/tezacaftor/ivacaftor藥效會增強，建議在開始併用Paxlovid的第一天與第五天服用Elexacaftor/tezacaftor/ivacaftor，並於療程結束4天後，恢復Elexacaftor/tezacaftor/ivacaftor原有劑量服用。}Elexacaftor/tezacaftor/ivacaftor藥效會增強，請依醫師指示減低劑量 ，並於 Paxlovid 療程結束4天後，依照醫囑恢復使用。",
  "oxybutynin": "{Oxybutynin藥效會增強，可能會增加抗膽鹼活性，高齡個案不建議併用。}Oxybutynin的藥效會增強，併用請監測相關不良反應（如眩暈、排尿困難等）。",
  "trastuzumab emtansine": "{DM1 (an active component of emtansine)濃度可能會因此上升，可能會增加藥物毒性，建議可由醫師評估延後使用，並於Paxlovid療程結束第三天再恢復使用}trastuzumab emtansine藥效會增強，請依醫師指示延後使用，並於 Paxlovid 療程結束3天後，依照醫囑恢復使用。",
  "upadacitinib": "{upadacitinib濃度可能會因此上升， 建議可由醫師評估降低使用劑量，並於Paxlovid療程結束第三天再恢復原本劑量使用}upadacitinib藥效會增強， 建議可由醫師評估降低使用劑量，並於Paxlovid療程結束第三天再恢復原本劑量使用。",
  "talazoparib": "{建議停藥, 並於Paxlovid療程結束第三天後再使用talazoparib/替代方案為調低talazoparib並監測毒性}請依照醫師指示減低劑量或停藥，並於Paxlovid停藥3天後，再調整或加回talazoparib原劑量",
  "tolterodine": "{歐洲仿單建議停藥, 並於Paxlovid療程結束第三天後再使用tolterodine/美國仿單建議tolterodine立即釋放錠最大可耐受劑量為1mg bid, 長效劑型最大可耐受劑量為2mg qd}請依照醫師指示減低劑量或停藥，並於Paxlovid停藥3天後，再調整或加回tolterodine原劑量",
  "gefitinib": "{Liverpool: 並用期間請監測gefitinib之相關毒性。}gefitinib藥效會增強，請依醫師指示觀察不良反應或調整劑量。",
  "macitentan": "{macitentan濃度可能會因此上升，不建議併用。建議可以使用其他治療肺動脈高壓之藥物，或改用其他抗病毒藥物。}",
  "maraviroc": "{maraviroc濃度可能會因此上升，如需併用，建議降低maraviroc劑量，當腎功能不良(ClCr<30或ESRD)時，不建議併用。}請依醫師指示使用或減低劑量。",
  "mefloquine": "{mefloquine濃度可能會因此上升，建議監測病人用藥之不良反應}請依醫師指示之劑量使用",
  "mexiletine": "{mexiletine濃度可能會因此上升，可能會增加藥物毒性 (nausea, dizziness, cardiac arrhythmias)，建議監測mexiletine藥物血中濃度並調降藥物劑量。}請依醫師指示使用或減低劑量。",
  "morphine": "{morphine濃度可能會因此上升，可能會增加呼吸抑制效果，請於併用期間減低劑量}請依醫師指示使用或減低劑量。",
  "nefazodone": "{nefazodone濃度可能會因此上升，可能會增加藥物毒性 (headache, dry mouth, nausea, somnolence, dizziness)，建議監測病人心臟、神經之不良反應}請依醫師指示之劑量使用",
  "oxycodone": "{oxycodone濃度可能會因此上升，可能會增加呼吸抑制效果，請於併用期間減低劑量，待Paxlovid療程結束後，視狀況逐步調整回原先劑量}請依醫師指示使用或減低劑量。",
  "posaconazole": "{可能會增加QT prolongation的風險。 }請依醫師指示之劑量使用，期間注意心率變化",
  "reboxetine": "{在台灣已被註銷。}",
  "rifabutin": "{rifabutin濃度可能會因此上升，建議rifabutin劑量減少75%正常劑量使用(如: 150 mg every other day or 3 times per week)，並監測病人用藥之不良反應}請依醫師指示使用或減低劑量。",
  "riociguat": "{riociguat濃度可能會因此上升，建議調降riociguat劑量，並監測低血壓之不良反應}請依醫師指示使用或減低劑量。",
  "risperidone": "{risperidone濃度可能會因此上升，可能會增加藥物毒性 (hypotension, sedation, extrapyramidal effects, arrhythmias)，建議調降risperidone劑量，並議監測病人之不良反應}請依醫師指示使用或減低劑量。"
};
